### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by gitstc** [telerik/ios-sdk#2]
Hi,

I downloaded the examples and opened them in Xcode 6.4, imported the trial TelerikUI.framework (UI for iOS Q3 2015) and tried to build the projects, but it failed with over than 200 errors.

Most of these errors say "Swift Compiler Error Expected ')'"

I even tried creating a new project and use the TelerikUI framework, but I get the following error:
"Parse Issue Expected ')'"

Does anybody else have the same problem? Do I need to use the latest version of Xcode?

**Comment by tzraikov** [comment]
Thank you for your interest in our controls. Yes, I confirm that you need Xcode 7 in order to compile our demo applications. All requirements for using Telerik UI for iOS are listed on this page:
http://www.telerik.com/download/ios-ui

Do not hesitate to contact us if you have other questions.
